language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1

    - php: 7.0
      env: COVERAGE=1

    - php: 7.0
      env: CAKEPHP_VERSION="3.5.*"

    - php: 7.0
      env: CAKEPHP_VERSION="3.6.*"

services:
  - mysql
  - postgresql
  
addons:
  postgresql: "9.4"

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ ! -z "$CAKEPHP_VERSION" ]]; then composer require --update-with-dependencies cakephp/cakephp:${CAKEPHP_VERSION}; fi

before_script:
  - mysql -e 'create database test;'
  - psql -c 'create database travis_ci_test;' -U postgres
  
script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' ]]; then vendor/bin/phpunit --exclude-group=onlyWindows; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=phpcs.xml.dist; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --exclude-group=onlyWindows --coverage-clover=clover.xml; fi
  
after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
