language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.2
      env: PHPCS=1
    - php: 7.2
      env: COVERAGE=1

services:
  - mysql
  - postgresql
  
addons:
  postgresql: "9.4"

install:
  - composer self-update -q
  - composer install --prefer-dist --no-interaction
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - composer show -i

before_script:
  - mysql -e 'create database test;'
  - psql -c 'create database travis_ci_test;' -U postgres
  
script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' ]]; then vendor/bin/phpunit --exclude-group=onlyWindows; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=phpcs.xml.dist; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --exclude-group=onlyWindows --coverage-clover=clover.xml; fi
  
after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
